INSERT into ingredients (
    name, ingredient, unit, amount
)
VALUES
    ("20th Century Cocktail", "gin", "oz", 1.5),
    ("20th Century Cocktail", "lemon juice", "oz", 0.75),
    ("20th Century Cocktail", "creme de cacao", "oz", 0.75),
    ("20th Century Cocktail", "Lillet Blanc or Cocchi Americano", "oz", 0.75),
    ("Abbey Cocktail", "gin", "oz", 1.5),
    ("Abbey Cocktail", "Lillet Blanc", "oz", 0.75),
    ("Abbey Cocktail", "orange juice", "oz", 0.75),
    ("Abbey Cocktail", "orange bitters", "dashes", 2),
    ("Abbey Cocktail", "cherry", "garnish", 1),
    ("Agave Old Fashioned", "tequila reposado", "oz", 2),
    ("Agave Old Fashioned", "agave nectar", "tsp", 1),
    ("Agave Old Fashioned", "Angostura bitters", "dashes", 2),
    ("Airmail", "aged rum", "oz", 1),
    ("Airmail", "lime juice", "oz", 0.5),
    ("Airmail", "honey syrup", "oz", 0.5),
    ("Airmail", "Champagne", "topping of", 1),
    ("Alabazam", "cognac", "oz", 1.5),
    ("Alabazam", "Cointreau", "oz", 0.5),
    ("Alabazam", "Angostura bitters", "oz", 0.25),
    ("Alabazam", "lemon juice", "oz", 0.25),
    ("Alabazam", "simple syrup", "oz", 0.25),
    ("Alaska Cocktail", "gin", "oz", 1.5),
    ("Alaska Cocktail", "Yellow Chartreuse", "oz", 0.75),
    ("Alaska Cocktail", "orange bitters", "dash", 1),
    ("Alaska Cocktail", "lemon twist", "garnish", 1),
    ("Angostura Fizz", "Angostura bitters", "oz", 1),
    ("Angostura Fizz", "lime juice", "oz", 1),
    ("Angostura Fizz", "simple syrup", "oz", 0.25),
    ("Angostura Fizz", "grenadine", "oz", 0.25),
    ("Angostura Fizz", "heavy cream", "oz", 0.5),
    ("Angostura Fizz", "egg white", "each", 1),
    ("Angostura Fizz", "soda water", "top", 1),
    ("Apple Toddy", "applejack", "oz", 2),
    ("Apple Toddy", "maple syrup", "tsp", 1),
    ("Apple Toddy", "Angostura bitters", "dashes", 2),
    ("Apple Toddy", "cinnamon tea", "oz", 3),
    ("Applejack Old Fashioned", "applejack", "oz", 2),
    ("Applejack Old Fashioned", "maple syrup", "tsp", 1),
    ("Applejack Old Fashioned", "Angostura bitters", "dashes", 2),
    ("Bee's Knees", "gin", "oz", 2),
    ("Bee's Knees", "lemon juice", "oz", 0.75),
    ("Bee's Knees", "honey simple syrup", "oz", 0.75),
    ("Bee's Knees", "lemon wheel", "garnish", 1),
    ("Bijou", "gin", "oz", 1),
    ("Bijou", "sweet vermouth", "oz", 1),
    ("Bijou", "Green Chartreuse", "oz", 1),
    ("Bijou", "orange bitters", "dash", 1),
    ("Bijou", "cherry", "garnish", 1),
    ("Bijou", "lemon twist", "garnish", 1),
    ("Bitter French", "gin", "oz", 1),
    ("Bitter French", "Campari", "oz", 0.25),
    ("Bitter French", "lemon juice", "oz", 0.5),
    ("Bitter French", "simple syrup", "oz", 0.5),
    ("Bitter French", "champagne", "oz", 2.5),
    ("Bitter Guiseppe", "Cynar", "oz", 2),
    ("Bitter Guiseppe", "sweet vermouth", "oz", 1),
    ("Bitter Guiseppe", "lemon juice", "oz", 0.25),
    ("Bitter Guiseppe", "orange bitter", "dashes", 6),
    ("Black Feather", "cognac", "oz", 2),
    ("Black Feather", "dry vermouth", "oz", 1),
    ("Black Feather", "Cointreau", "oz", 0.5),
    ("Black Feather", "Angostura bitters", "dash", 1),
    ("Blackthorn", "gin", "oz", 1.5),
    ("Blackthorn", "sweet vermouth", "oz", 0.75),
    ("Blackthorn", "sloe gin", "oz", 0.75),
    ("Blackthorn", "orange bitters", "dashes", 2),
    ("Blackthorn", "orange twist", "garnish", 1),
    ("Blonde Redhead", "aperol", "oz", 3),
    ("Blonde Redhead", "grapefruit juice", "oz", 1),
    ("Blonde Redhead", "lemon juice", "oz", 0.25),
    ("Blonde Redhead", "club soda", "oz", 3),
    ("Blood & Sand", "scotch", "oz", 1),
    ("Blood & Sand", "Cherry Heering", "oz", 0.5),
    ("Blood & Sand", "orange juice", "oz", 0.75),
    ("Blood & Sand", "brandied cherry", "garnish", 1),
    ("Bobby Burns", "scotch", "oz", 2),
    ("Bobby Burns", "sweet vermouth", "oz", 0.75),
    ("Bobby Burns", "Drambuie", "oz", 0.25),
    ("Bobby Burns", "Angostura bitters", "dash", 1),
    ("Boulevardier", "rye whiskey", "oz", 1.5),
    ("Boulevardier", "sweet vermouth", "oz", 1),
    ("Boulevardier", "Campari", "oz", 1),
    ("Boulevardier", "orange twist", "garnish", 1),
    ("Bourbon Toddy", "bourbon", "oz", 2),
    ("Bourbon Toddy", "simple syrup", "tsp", 1),
    ("Bourbon Toddy", "Angostura bitters", "dashes", 2),
    ("Bourbon Toddy", "boiling water", "oz", 3),
    ("Brandy 75", "cognac", "oz", 1),
    ("Brandy 75", "lemon juice", "oz", 0.5),
    ("Brandy 75", "simple syrup", "oz", 0.5),
    ("Brandy 75", "champagne", "oz", 2.5),
    ("Brandy Alexander", "cognac", "oz", 2),
    ("Brandy Alexander", "heavy cream", "oz", 1),
    ("Brandy Alexander", "simple syrup", "oz", 0.25),
    ("Brandy Alexander", "grated nutmeg", "garnish", 1),
    ("Brandy Crusta", "cognac", "oz", 2),
    ("Brandy Crusta", "lemon juice", "oz", 0.5),
    ("Brandy Crusta", "orange curacao", "oz", 0.5),
    ("Brandy Crusta", "Luxardo Maraschino", "oz", 0.25),
    ("Brandy Crusta", "lemon spiral", "garnish", 1),
    ("Brandy Crusta", "sugar", "rim", 1),
    ("Brooklyn", "rye whiskey", "oz", 2),
    ("Brooklyn", "Amer Picon", "oz", 0.5),
    ("Brooklyn", "dry vermouth", "oz", 0.5),
    ("Brooklyn", "Luxardo Maraschino", "oz", 0.25),
    ("Brooklyn", "Angostura bitters", "dash", 1),
    ("Brooklyn", "cherry", "garnish", 1),
    ("Brown Derby", "grapefruit juice", "oz", 1),
    ("Brown Derby", "honey simple syrup", "oz", 0.5),
    ("Brown Derby", "grapefruit twist", "garnish", 1),
    ("Brown Derby", "bourbon or rye whiskey", "oz", 2),
    ("Caipirinha", "lime", "wedges", 6),
    ("Caipirinha", "simple syrup", "oz", 0.75),
    ("Caipirinha", "sugar", "cube", 1),
    ("Caipirinha", "cachaca", "oz", 2),
    ("Champagne Cocktail", "champagne", "oz", 5),
    ("Champagne Cocktail", "sugar", "cube", 1),
    ("Champagne Cocktail", "Angostura bitters", "dashes", 5),
    ("Champagne Cocktail", "lemon twist", "garnish", 1),
    ("Champs Elysees", "cognac", "oz", 2),
    ("Champs Elysees", "Cointreau", "oz", 0.75),
    ("Champs Elysees", "green Chartreuse", "tsp", 1),
    ("Champs Elysees", "lemon juice", "oz", 0.75),
    ("Champs Elysees", "simple syrup", "oz", 0.25),
    ("Champs Elysees", "Angostura bitters", "dashes", 2),
    ("Champs-Elysees", "cognac", "oz", 2),
    ("Champs-Elysees", "green Chartreuse", "oz", 0.5),
    ("Champs-Elysees", "lemon juice", "oz", 0.75),
    ("Champs-Elysees", "simple syrup", "oz", 0.5),
    ("Champs-Elysees", "Angostura bitters", "dashes", 2),
    ("Champs-Elysees", "lemon", "twist", 1),
    ("Corn 'n' Oil", "blackstrap rum", "oz", 2),
    ("Corn 'n' Oil", "falernum", "oz", 0.5),
    ("Corn 'n' Oil", "lime juice", "oz", 0.25),
    ("Corn 'n' Oil", "Angostura bitters", "dashes", 3),
    ("Corn 'n' Oil", "lime wedge", "garnish", 1),
    ("Corpse Reviver #2", "gin", "oz", 0.75),
    ("Corpse Reviver #2", "lemon juice", "oz", 0.75),
    ("Corpse Reviver #2", "Cointreau", "oz", 0.75),
    ("Corpse Reviver #2", "Lillet Blanc", "oz", 0.75),
    ("Corpse Reviver #2", "absinthe", "dashes", 3),
    ("Corpse Reviver #2", "orange twist", "garnish", 1),
    ("Cosmopolitan", "Absolut Citron vodka", "oz", 1.5),
    ("Cosmopolitan", "Cointreau", "oz", 0.75),
    ("Cosmopolitan", "cranberry juice", "oz", 0.75),
    ("Cosmopolitan", "lime juice", "oz", 0.5),
    ("Cosmopolitan", "orange twist", "garnish", 1),
    ("Cricket Ball", "sugar", "cube", 1),
    ("Cricket Ball", "Peychaud's bitters", "dashes", 3),
    ("Cricket Ball", "Fee Brothers rhubarb bitters", "dashes", 3),
    ("Cricket Ball", "Lillet Rouge", "oz", 1),
    ("Cricket Ball", "champagne", "oz", 3),
    ("Cricket Ball", "lemon twist", "garnish", 1),
    ("Daiquiri", "white rum", "oz", 2),
    ("Daiquiri", "lime juice", "oz", 0.75),
    ("Daiquiri", "simple syrup", "oz", 0.75),
    ("Dark & Stormy", "dark rum", "oz", 2),
    ("Dark & Stormy", "lime juice", "oz", 0.75),
    ("Dark & Stormy", "ginger beer", "oz", 4),
    ("Dark & Stormy", "lime", "wheel garnish", 1),
    ("De La Louisiane", "rye whiskey", "oz", 2),
    ("De La Louisiane", "Benedictine", "oz", 0.5),
    ("De La Louisiane", "sweet vermouth", "oz", 0.5),
    ("De La Louisiane", "Peychaud's bitters", "dashes", 3),
    ("De La Louisiane", "Angostura bitters", "dashes", 3),
    ("De La Louisiane", "absinthe", "dashes", 3),
    ("De La Louisiane", "cherry", "garnish", 1),
    ("Diamondback", "rye whiskey", "oz", 2),
    ("Diamondback", "apple brandy", "oz", 0.5),
    ("Diamondback", "yellow Chartreuse", "oz", 0.5),
    ("Fancy-Free", "rye whiskey", "oz", 2),
    ("Fancy-Free", "Luxardo maraschino", "oz", 0.5),
    ("Fancy-Free", "Angostura bitters", "dash", 1),
    ("Fancy-Free", "orange bitters", "dash", 1),
    ("Fancy-Free", "orange", "twist", 1),
    ("Fitzgerald", "gin", "oz", 2),
    ("Fitzgerald", "lemon juice", "oz", 0.75),
    ("Fitzgerald", "simple syrup", "oz", 1),
    ("Fitzgerald", "Angostura bitters", "dashes", 2),
    ("Fitzgerald", "lemon", "wedge", 1),
    ("French 75", "gin", "oz", 1),
    ("French 75", "lemon juice", "oz", 0.5),
    ("French 75", "simple syrup", "oz", 0.5),
    ("French 75", "champagne", "oz", 2.5),
    ("French 95", "bourbon", "oz", 2),
    ("French 95", "lemon juice", "oz", 0.75),
    ("French 95", "simple syrup", "oz", 0.5),
    ("French 95", "champagne", "oz", 2.5),
    ("Gargoyle and Spire", "gin", "oz", 1),
    ("Gargoyle and Spire", "Strega", "oz", 0.75),
    ("Gargoyle and Spire", "simple syrup", "oz", 0.25),
    ("Gargoyle and Spire", "orange bitters", "dashes", 2),
    ("Gargoyle and Spire", "champagne", "oz", 2),
    ("Gargoyle and Spire", "orange twist", "garnish", 1),
    ("Gimlet", "gin", "oz", 2),
    ("Gimlet", "lime juice", "oz", 0.75),
    ("Gimlet", "simple syrup", "oz", 0.75),
    ("Gimlet", "lime wheel", "garnish", 1),
    ("Gin Fizz", "gin", "oz", 2),
    ("Gin Fizz", "lemon juice", "oz", 0.75),
    ("Gin Fizz", "simple syrup", "oz", 0.75),
    ("Gin Fizz", "white", "egg", 1),
    ("Gin Rickey", "gin", "oz", 2),
    ("Gin Rickey", "lime juice", "oz", 1),
    ("Gin Rickey", "simple syrup", "oz", 0.5),
    ("Gin Rickey", "lime", "wedge", 1),
    ("Gold Rush", "bourbon whiskey", "oz", 2),
    ("Gold Rush", "lemon juice", "oz", 0.75),
    ("Gold Rush", "honey simple syrup", "oz", 0.75),
    ("Grasshopper", "mint", "muddled leaves", 8),
    ("Grasshopper", "creme de menthe", "oz", 1),
    ("Grasshopper", "heavy cream", "oz", 1),
    ("Grasshopper", "mint sprig", "garnish", 1),
    ("Hanky Panky", "gin", "oz", 2),
    ("Hanky Panky", "sweet vermouth", "oz", 1),
    ("Hanky Panky", "Fernet Branca", "oz", 0.25),
    ("Hanky Panky", "orange twist", "garnish", 1),
    ("Harvard Cocktail", "cognac", "oz", 1.5),
    ("Harvard Cocktail", "sweet vermouth", "oz", 0.75),
    ("Harvard Cocktail", "lemon juice", "oz", 0.25),
    ("Harvard Cocktail", "grenadine", "teaspoon", 1),
    ("Harvard Cocktail", "Angostura bitters", "dashes", 3),
    ("Harvard Cocktail", "lemon twist", "garnish", 1),
    ("Hemingway Daiquiri", "white rum", "oz", 2),
    ("Hemingway Daiquiri", "lime juice", "oz", 0.75),
    ("Hemingway Daiquiri", "grapefruit juice", "oz", 0.5),
    ("Hemingway Daiquiri", "Luxardo Maraschino", "oz", 0.5),
    ("Hemingway Daiquiri", "salt", "pinch", 1),
    ("Hemingway Daiquiri", "lime wheel", "garnish", 1),
    ("Honeysuckle", "white rum", "oz", 2),
    ("Honeysuckle", "lime juice", "oz", 0.75),
    ("Honeysuckle", "honey simple syrup", "oz", 0.75),
    ("Honeysuckle", "lime wheel", "garnish", 1),
    ("Hot Toddy", "rye", "oz", 2),
    ("Hot Toddy", "simple syrup", "tsp", 1),
    ("Hot Toddy", "Angostura bitters", "dashes", 2),
    ("Hot Toddy", "boiling water", "oz", 3),
    ("Improved Whiskey Cocktail", "rye whiskey", "oz", 2),
    ("Improved Whiskey Cocktail", "simple syrup", "oz", 0.25),
    ("Improved Whiskey Cocktail", "Luxardo Maraschino", "oz", 0.25),
    ("Improved Whiskey Cocktail", "Angostura bitters", "dashes", 2),
    ("Improved Whiskey Cocktail", "absinthe", "rinse", 1),
    ("Improved Whiskey Cocktail", "lemon twist", "garnish", 1),
    ("Japanese Cocktail", "cognac", "oz", 2),
    ("Japanese Cocktail", "orgeat", "oz", 0.5),
    ("Japanese Cocktail", "Angostura bitters", "dashes", 3),
    ("Japanese Cocktail", "lemon twist", "garnish", 1),
    ("Jersey Julep", "mint leaves", "each", 10),
    ("Jersey Julep", "maple syrup", "oz", 0.5),
    ("Jersey Julep", "apple brandy", "oz", 2),
    ("La Rosa", "strawberry", "each", 1),
    ("La Rosa", "simple syrup", "oz", 0.5),
    ("La Rosa", "tequila blanco", "oz", 2),
    ("La Rosa", "amaro", "oz", 1),
    ("La Rosa", "lemon juice", "oz", 0.75),
    ("La Rosa", "pink champagne", "oz", 1.5),
    ("La Rosita", "reposado tequila", "oz", 2),
    ("La Rosita", "Campari", "oz", 0.5),
    ("La Rosita", "sweet vermouth", "oz", 0.5),
    ("La Rosita", "dry vermouth", "oz", 0.5),
    ("La Rosita", "Angostura bitters", "dashes", 2),
    ("La Rosita", "orange", "twist", 1),
    ("Last Word", "gin", "oz", 0.75),
    ("Last Word", "Green Chartreuse", "oz", 0.75),
    ("Last Word", "Luxardo Maraschino", "oz", 0.75),
    ("Last Word", "lime juice", "oz", 0.75),
    ("Last Word", "salt", "pinch", 1),
    ("Lucien Gaudin", "gin", "oz", 1.5),
    ("Lucien Gaudin", "dry vermouth", "oz", 0.5),
    ("Lucien Gaudin", "Campari", "oz", 0.5),
    ("Lucien Gaudin", "Cointreau", "oz", 0.5),
    ("Lucien Gaudin", "lemon", "twist", 1),
    ("Manhattan", "rye", "oz", 2),
    ("Manhattan", "sweet vermouth", "oz", 0.75),
    ("Manhattan", "Angostura bitters", "dashes", 2),
    ("Manhattan", "brandied cherry", "garnish", 1),
    ("Margarita", "tequila", "oz", 2),
    ("Margarita", "Cointreau", "oz", 0.75),
    ("Margarita", "lime juice", "oz", 1),
    ("Margarita", "simple syrup or agave nectar", "oz", 0.5),
    ("Margarita", "salt", "rim", 1),
    ("Martinez", "gin", "oz", 1.5),
    ("Martinez", "sweet vermouth", "oz", 1),
    ("Martinez", "Luxardo", "tsp", 1),
    ("Martinez", "Angostura bitters", "dashes", 2),
    ("Martini", "gin", "oz", 2.5),
    ("Martini", "dry vermouth", "oz", 0.75),
    ("Martini", "orange bitters", "dash", 1),
    ("Martini", "lemon twist", "garnish", 1),
    ("Mint Julep", "bourbon", "oz", 2),
    ("Mint Julep", "simple syrup", "oz", 0.75),
    ("Mint Julep", "mint bouquet", "muddled", 1),
    ("Mojito", "mint leaves", "muddled", 6),
    ("Mojito", "simple syrup", "oz", 0.75),
    ("Mojito", "rum", "oz", 2),
    ("Mojito", "lime juice", "oz", 1),
    ("Mojito", "Angostura bitters", "drops", 2),
    ("Mojito", "mint bouquet", "garnish", 1),
    ("Moscow Mule", "vodka", "oz", 2),
    ("Moscow Mule", "ginger syrup", "oz", 0.75),
    ("Moscow Mule", "lime juice", "oz", 0.75),
    ("Moscow Mule", "club soda", "oz", 2),
    ("Negroni", "gin", "oz", 1),
    ("Negroni", "sweet vermouth", "oz", 1),
    ("Negroni", "Campari", "oz", 1),
    ("Negroni", "orange twist", "garnish", 1),
    ("Old Fashioned", "rye", "oz", 2),
    ("Old Fashioned", "simple syrup", "tsp", 1),
    ("Old Fashioned", "Angostura bitters", "dashes", 2),
    ("Old Hickory", "sweet vermouth", "oz", 1.5),
    ("Old Hickory", "dry vermouth", "oz", 1.5),
    ("Old Hickory", "Peychaud's bitters", "dash", 1),
    ("Old Hickory", "orange bitters", "dash", 1),
    ("Old Hickory", "lemon twist", "garnish", 1),
    ("Old Pal", "rye whiskey", "oz", 2),
    ("Old Pal", "dry vermouth", "oz", 0.75),
    ("Old Pal", "Campari", "oz", 0.75),
    ("Old Pal", "lemon twist", "garnish", 1),
    ("Paloma", "tequila blanco", "oz", 2),
    ("Paloma", "grapefruit juice", "oz", 1),
    ("Paloma", "lime juice", "oz", 0.75),
    ("Paloma", "simple syrup", "oz", 0.75),
    ("Paloma", "club soda", "oz", 1.5),
    ("Paloma", "lime wheel", "garnish", 1),
    ("Pegu Club", "gin", "oz", 2),
    ("Pegu Club", "lime juice", "oz", 0.5),
    ("Pegu Club", "orange curacao", "oz", 0.75),
    ("Pegu Club", "Angostura bitters", "dash", 1),
    ("Pegu Club", "orange bitters", "dash", 1),
    ("Penicillin", "blended scotch whiskey", "oz", 2),
    ("Penicillin", "lemon juice", "oz", 0.75),
    ("Penicillin", "honey simple syrup", "oz", 0.75),
    ("Penicillin", "fresh ginger", "slices", 3),
    ("Penicillin", "Islay scotch whiskey", "oz", 0.25),
    ("Ping-Pong Cocktail", "sloe gin", "oz", 2),
    ("Ping-Pong Cocktail", "dry vermouth", "oz", 0.5),
    ("Ping-Pong Cocktail", "bitter sweet vermouth or amaro", "oz", 0.5),
    ("Ping-Pong Cocktail", "orange bitters", "dashes", 2),
    ("Ping-Pong Cocktail", "lemon twist", "garnish", 1),
    ("Pink Gin", "gin", "oz", 2),
    ("Pink Gin", "Angostura bitters", "dashes", 5),
    ("Pisco 75", "strawberry", "each", 1),
    ("Pisco 75", "simple syrup", "oz", 0.5),
    ("Pisco 75", "pisco", "oz", 1),
    ("Pisco 75", "lemon juice", "oz", 0.5),
    ("Pisco 75", "champagne", "oz", 2.5),
    ("Pisco Sour", "pisco", "oz", 2),
    ("Pisco Sour", "egg white", "oz", 1),
    ("Pisco Sour", "simple syrup", "oz", 0.75),
    ("Pisco Sour", "lime juice", "oz", 0.75),
    ("Pisco Sour", "Angostura bitters", "drops", 3),
    ("Preakness", "bourbon", "oz", 1.5),
    ("Preakness", "sweet vermouth", "oz", 0.75),
    ("Preakness", "Benedictine", "oz", 0.25),
    ("Preakness", "Angostura bitters", "dashes", 2),
    ("Preakness", "orange twist", "garnish", 1),
    ("Queen's Park Swizzle", "mint leaves", "muddled", 10),
    ("Queen's Park Swizzle", "simple syrup", "oz", 0.75),
    ("Queen's Park Swizzle", "sugar", "cube", 1),
    ("Queen's Park Swizzle", "aged rum", "oz", 2),
    ("Queen's Park Swizzle", "lime juice", "oz", 1),
    ("Queen's Park Swizzle", "Peychaud's bitters", "dashes", 4),
    ("Queen's Park Swizzle", "Angostura bitters", "dashes", 4),
    ("Queen's Park Swizzle", "mint sprig", "garnish", 1),
    ("Ramos Gin Fizz", "Old Tom gin", "oz", 1.5),
    ("Ramos Gin Fizz", "egg white", "each", 1),
    ("Ramos Gin Fizz", "heavy cream", "oz", 1),
    ("Ramos Gin Fizz", "orange flower water", "dashes", 3),
    ("Ramos Gin Fizz", "simple syrup", "oz", 0.5),
    ("Ramos Gin Fizz", "lemon juice", "oz", 0.5),
    ("Ramos Gin Fizz", "lime juice", "oz", 0.5),
    ("Ramos Gin Fizz", "soda water", "oz", 1),
    ("Ramos Gin Fizz", "orange wheel", "garnish", 1),
    ("Rob Roy", "blended scotch whiskey", "oz", 2.5),
    ("Rob Roy", "sweet vermouth", "oz", 0.75),
    ("Rob Roy", "Angostura bitters", "dashes", 2),
    ("Rob Roy", "lemon twist", "garnish", 1),
    ("Rum 75", "aged rum", "oz", 1),
    ("Rum 75", "lemon juice", "oz", 0.5),
    ("Rum 75", "simple syrup", "oz", 0.5),
    ("Rum 75", "champagne", "oz", 2.5),
    ("Rum Old Fashioned", "aged rum", "oz", 2),
    ("Rum Old Fashioned", "simple syrup", "tsp", 1),
    ("Rum Old Fashioned", "Angostura bitters", "dashes", 2),
    ("Rum Toddy", "aged rum", "oz", 2),
    ("Rum Toddy", "simple syrup", "tsp", 1),
    ("Rum Toddy", "Angostura bitters", "dashes", 2),
    ("Rum Toddy", "boiling water", "oz", 3),
    ("Rusty Nail", "blended scotch whiskey", "oz", 2),
    ("Rusty Nail", "Drambuie", "oz", 0.5),
    ("Rusty Nail", "lemon peel", "garnish", 1),
    ("Sawyer", "gin", "oz", 2),
    ("Sawyer", "lime juice", "oz", 0.5),
    ("Sawyer", "simple syrup", "oz", 0.5),
    ("Sawyer", "Angostura bitters", "dashes", 14),
    ("Sawyer", "Peychaud's bitters", "dashes", 7),
    ("Sawyer", "orange bitters", "dashes", 7),
    ("Sazerac", "rye whiskey", "oz", 2),
    ("Sazerac", "simple syrup", "oz", 0.25),
    ("Sazerac", "Peychaud's bitters", "dashes", 4),
    ("Sazerac", "absinthe", "rinse", 1),
    ("Sazerac", "lemon peel", "garnish", 1),
    ("Scofflaw Cocktail", "rye whiskey", "oz", 1.5),
    ("Scofflaw Cocktail", "dry vermouth", "oz", 1),
    ("Scofflaw Cocktail", "lemon juice", "oz", 0.75),
    ("Scofflaw Cocktail", "grenadine", "oz", 0.75),
    ("Scofflaw Cocktail", "orange bitter", "dash", 1),
    ("Scofflaw Cocktail", "orange twist", "garnish", 1),
    ("Scotch Old Fashioned", "scotch", "oz", 2),
    ("Scotch Old Fashioned", "honey", "tsp", 1),
    ("Scotch Old Fashioned", "Angostura bitters", "dashes", 2),
    ("Scotch Toddy", "scotch", "oz", 2),
    ("Scotch Toddy", "honey", "tbl", 1),
    ("Scotch Toddy", "lemon juice", "oz", 0.5),
    ("Scotch Toddy", "boiling water", "oz", 3),
    ("Seelbach Cocktail", "bourbon whiskey", "oz", 1),
    ("Seelbach Cocktail", "Cointreau", "oz", 0.5),
    ("Seelbach Cocktail", "Angostura bitters", "dashes", 7),
    ("Seelbach Cocktail", "Peychaud's bitters", "dashes", 7),
    ("Seelbach Cocktail", "champagne", "oz", 2),
    ("Seelbach Cocktail", "orange twist", "garnish", 1),
    ("Sidecar", "cognac", "oz", 2),
    ("Sidecar", "Cointreau", "oz", 1),
    ("Sidecar", "lemon juice", "oz", 0.75),
    ("South Side", "mint leaves", "muddled", 5),
    ("South Side", "gin", "oz", 2),
    ("South Side", "lime juice", "oz", 0.75),
    ("South Side", "simple syrup", "oz", 0.5),
    ("South Side", "Angostura bitters", "dashes", 2),
    ("South Side", "mint sprig", "garnish", 1),
    ("Southland Sipper", "strawberry", "each", 1),
    ("Southland Sipper", "simple syrup", "oz", 0.75),
    ("Southland Sipper", "rye", "oz", 1.5),
    ("Southland Sipper", "Benedictine", "oz", 0.25),
    ("Southland Sipper", "lemon juice", "oz", 0.75),
    ("Southland Sipper", "Angostura bitters", "dashes", 2),
    ("Southland Sipper", "club soda", "oz", 2),
    ("Southside Cocktail", "gin", "oz", 2),
    ("Southside Cocktail", "mint leaves", "each", 8),
    ("Southside Cocktail", "lemon juice", "oz", 0.75),
    ("Southside Cocktail", "simple syrup", "oz", 0.75),
    ("Southside Cocktail", "club soda", "oz", 2),
    ("Southside Fizz", "mint leaves", "each", 8),
    ("Southside Fizz", "cucumber wheel", "each", 2),
    ("Southside Fizz", "simple syrup", "oz", 1),
    ("Southside Fizz", "gin", "oz", 2),
    ("Southside Fizz", "lime juice", "oz", 0.75),
    ("Southside Fizz", "club soda", "oz", 2),
    ("Stinger", "cognac", "oz", 2),
    ("Stinger", "creme de menthe", "oz", 0.5),
    ("Stinger", "simple syrup", "tsp", 1),
    ("Stinger", "mint sprig", "garnish", 1),
    ("Summer Negroni", "gin", "oz", 1),
    ("Summer Negroni", "aperol", "oz", 1),
    ("Summer Negroni", "bianco vermouth", "oz", 1),
    ("Tailspin", "Capmari", "rinse", 1),
    ("Tailspin", "gin", "oz", 1.5),
    ("Tailspin", "sweet vermouth", "oz", 1),
    ("Tailspin", "green Chartreuse", "oz", 1),
    ("Tailspin", "orange bitters", "dashes", 2),
    ("Tailspin", "lemon twist", "garnish", 1),
    ("Tequila 75", "tequila blanco", "oz", 1),
    ("Tequila 75", "lemon juice", "oz", 0.5),
    ("Tequila 75", "agave nectar", "oz", 0.5),
    ("Tequila 75", "champagne", "oz", 2.5),
    ("The Bamboo", "sherry", "oz", 1.5),
    ("The Bamboo", "dry vermouth", "oz", 1.5),
    ("The Bamboo", "orange bitters", "dashes", 2),
    ("The Bamboo", "Angostura bitters", "dashes", 1),
    ("The Bitter Handshake", "Fernet Branca", "oz", 1),
    ("The Bitter Handshake", "blood orange juice reduction", "oz", 1),
    ("The Bitter Handshake", "rye whiskey simple syrup", "oz", 1),
    ("The Bitter Handshake", "orange spiral", "garnish", 1),
    ("Tom Collins", "gin", "oz", 2),
    ("Tom Collins", "lemon juice", "oz", 0.75),
    ("Tom Collins", "simple syrup", "oz", 0.75),
    ("Tom Collins", "club soda", "oz", 2),
    ("Toronto", "rye whiskey", "oz", 2),
    ("Toronto", "Fernet Branca", "oz", 0.25),
    ("Toronto", "simple syrup", "oz", 0.25),
    ("Toronto", "Angostura bitters", "dashes", 2),
    ("Toronto", "orange twist", "garnish", 1),
    ("Trident", "dry sherry", "oz", 1),
    ("Trident", "Cynar", "oz", 1),
    ("Trident", "aquavit", "oz", 1),
    ("Trident", "Fee Brothers peach bitters", "dashes", 2),
    ("Vesper", "gin", "oz", 1.5),
    ("Vesper", "vodka", "oz", 0.75),
    ("Vesper", "Cocchi Americano", "oz", 0.5),
    ("Vesper", "lemon twist", "garnish", 1),
    ("Vieux Carre", "rye whiskey", "oz", 1),
    ("Vieux Carre", "cognac", "oz", 1),
    ("Vieux Carre", "sweet vermouth", "oz", 0.75),
    ("Vieux Carre", "Benedictine", "oz", 0.25),
    ("Vieux Carre", "Angostura bitters", "dash", 1),
    ("Vieux Carre", "Peychaud's bitters", "dash", 1),
    ("Ward 8", "rye", "oz", 2),
    ("Ward 8", "lemon juice", "oz", 0.5),
    ("Ward 8", "orange juice", "oz", 0.5),
    ("Ward 8", "simple syrup", "oz", 0.5),
    ("Ward 8", "pomegranate molasses", "tsp", 1),
    ("Whiskey Sour", "rye whiskey", "oz", 2),
    ("Whiskey Sour", "egg white", "oz", 1),
    ("Whiskey Sour", "simple syrup", "oz", 0.75),
    ("Whiskey Sour", "lemon juice", "oz", 0.625),
    ("Whiskey Sour", "salt", "pinch", 1),
    ("Widow's Kiss", "apple brandy", "oz", 2),
    ("Widow's Kiss", "Benedictine", "oz", 0.25),
    ("Widow's Kiss", "Yellow Chartreuse", "oz", 0.25),
    ("Widow's Kiss", "Angostura bitters", "dashes", 2),
    ("Zim Zala Bim", "reposado tequila", "oz", 2),
    ("Zim Zala Bim", "orange bitters", "teaspoons", 2),
    ("Zim Zala Bim", "St Germain", "teaspoons", 2),
    ("Zim Zala Bim", "sugar", "teaspoons", 1),
    ("Zim Zala Bim", "lemon twist", "garnish", 1),
    ("Black Manhattan", "rye", "oz", 2),
    ("Black Manhattan", "Averna or other amaro", "oz", 0.75),
    ("Black Manhattan", "Angostura bitters", "dashes", 2),
    ("Black Manhattan", "brandied cherry", "garnish", 1)
;
